### ISSUE TITLE
Start onderzoek - @YaraPrins

### ISSUE THREAD

**Issue by YaraPrins** [Michiel1998/Matchingapp-team2#18]
Onderzoek bijna af, alleen nog implementeren in project.

@Marengd - heb jij alles duidelijk staan wat in elkaar genest moet worden / opgedeeld moet worden in partials van het CSS bestand?

**Comment by Marengd** [comment]
@YaraPrins, iedere pagina heeft een eigen CSS bestand. Heb even gekeken, denk dat je het best aan de slag kan gaan in de "Likes.css" en "Discover.css". 

E![Schermafbeelding 2022-03-30 om 21 40 22](https://user-images.githubusercontent.com/94312410/160917285-3dbc41b0-8805-454e-b2df-e3cfcff57cab.png)
n dan zou je het toe kunnen passen op de kaarten waar de kroegen instaan.

**Comment by YaraPrins** [comment]
Alleen nog in de wiki beschrijven hoe het implementeren allemaal ging, daar ga ik gelijk even mee aan de slag! Ik sluit daarom deze Issue.
